{
 "title": "Producer Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Latency for /counter/:bannerID",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{path=\"/counter/:bannerID\"}[1m]) / rate(http_request_duration_seconds_count{path=\"/counter/:bannerID\"}[1m])",
     "legendFormat": "Average latency (s)"
    }
   ]
  },
  {
   "title": "RPS for /counter/:bannerID",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=\"/counter/:bannerID\"}[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "95th percentile Latency",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/counter/:bannerID\"}[1m])) by (le))",
     "legendFormat": "p95 latency (s)"
    }
   ]
  }
 ]
}